### ISSUE TITLE
Callback for instruction end is stuck in endless loop

### ISSUE THREAD

**Issue by bob-hendrix** [Cisco-Talos/pyrebox#93] opened 2019-09-19 16:01 UTC
Originally I had the issue that guest_agent wasn't working on win7SP1x64 . It crashed\ printed that it's not working under pyrebox, while guest_agent.py (I used the one with debug info that you provided in another issue) saw that is was working. I think pyrebox fails to increment RIP correctly when it detects version opcode.

However, when trying to debug original issue, I stubmled upon another one. When I add a callback on instruction beginning\end, it triggers on some adress inside the kernel and then follows something looking like an infinite loop either forever or until i remove this callback somehow. And when this is happening, guest is frozen and monitored process doesn't do anything (and resumes what it was supposed to be doing as soon as I do rm_callback for instruction begin callback). Maybe this issue is related to my original one, but I dont undersnad how to debug it.

**Comment by xabiugarte** [comment] 2019-09-20 05:33
Hi Bob, 

Can you post the script so that I can try to reproduce the issue and debug it myself?

Thanks!

**Comment by bob-hendrix** [comment] 2019-09-20 07:40
`from __future__ import print_function
from ipython_shell import start_shell
import api
from api import CallbackManager


# requirements = ["plugins.guest_agent"]

# Callback manager
cm = None
# Printer
pyrebox_print = None

# Global variables
# If we want to keep some global var shared between different callback
# functions that is preserved from call to call, we must define
# it as a global
insns_pased = 0
procs_created = 0
target_procname = "hello_world_"
# target_procname = "win_agent"
in_kernel = False

def handle_new_proc(params):
    global pyrebox_print
    global procs_created
    global target_procname
    global cm
    global in_kernel

    pid = params["pid"]
    pgd = params["pgd"]
    name = params["name"]

    pyrebox_print("New process created! pid: %x, pgd: %x, name: %s" % (pid, pgd, name))
    procs_created += 1
    # For instance, we can start the shell whenever a process is created
    if target_procname != "" and target_procname.lower() in name.lower():
        cm.add_callback(CallbackManager.INSN_BEGIN_CB, handle_insn_begin, name="insn_begin")
        # In order to start a shell, we just need to call start_shell()
        in_kernel = api.is_kernel_running()
        pyrebox_print("Starting a shell after the %s process has been created. In kernel: %s\n" % (name, in_kernel))
        api.start_monitoring_process(pgd)
        start_shell()


def handle_insn_begin(params):
    global cm
    global insns_pased
    global in_kernel
    pyrebox_print("Handling instruction begin. All params: %s\n" % params.keys())
    insns_pased += 1
    if insns_pased > 1000000:
        pyrebox_print("Too many instructions\n")
        cm.rm_callback("insn_begin")
    if insns_pased == 10000:
        start_shell()


    cpu_index = params["cpu_index"]
    cpu = params["cpu"]

    pgd = api.get_running_process(cpu_index)
    pyrebox_print("INSN No: %d, pgd: %x,PC: %x, RIP: %x\n" % (insns_pased, pgd, cpu.PC, cpu.RIP))
    if api.is_kernel_running() is not in_kernel:
        in_kernel = api.is_kernel_running()
        pyrebox_print("Moved in/out of kernel. Running shell\n")
        start_shell()

    # start_shell()

def clean():
    '''
    Clean up everything.

    This function is called when the script is
    unloaded.

    It is necessary to call the clean() function
    in  the callback manager, that will unregister
    all the registered callbacks. Otherwise, the
    next time the callback is triggered, it will
    try to call to a non existent function and
    PyREbox will crash.

    Here you may clean or log whatever you consider
    necessary.
    '''
    global cm
    print("[*]    Cleaning module")
    cm.clean()
    print("[*]    Cleaned module")


def initialize_callbacks(module_hdl, printer):
    '''
    Initilize callbacks for this module. This function
    will be triggered whenever import_module command
    is triggered.
    '''
    global cm
    global pyrebox_print
    # Initialize printer function (global var), that we can use to print
    # text that is associated to our script
    pyrebox_print = printer
    pyrebox_print("[*]    Initializing callbacks")
    # Initialize the callback manager, and register a couple of named
    # callbacks.
    cm = CallbackManager(module_hdl, new_style=True)
    cm.add_callback(CallbackManager.CREATEPROC_CB, handle_new_proc, name="vmi_new_proc")
    # cm.add_callback(CallbackManager.INSN_BEGIN_CB, handle_insn_begin, name="insn_begin")
    pyrebox_print("[*]    Initialized callbacks")


if __name__ == "__main__":
    print("[*] Loading python module %s" % (__file__))
`

**Comment by bob-hendrix** [comment] 2019-09-20 07:42
```
from __future__ import print_function
from ipython_shell import start_shell
import api
from api import CallbackManager


# requirements = ["plugins.guest_agent"]

# Callback manager
cm = None
# Printer
pyrebox_print = None

# Global variables
# If we want to keep some global var shared between different callback
# functions that is preserved from call to call, we must define
# it as a global
insns_pased = 0
procs_created = 0
target_procname = "hello_world_"
# target_procname = "win_agent"
in_kernel = False

def handle_new_proc(params):
    global pyrebox_print
    global procs_created
    global target_procname
    global cm
    global in_kernel

    pid = params["pid"]
    pgd = params["pgd"]
    name = params["name"]

    pyrebox_print("New process created! pid: %x, pgd: %x, name: %s" % (pid, pgd, name))
    procs_created += 1
    # For instance, we can start the shell whenever a process is created
    if target_procname != "" and target_procname.lower() in name.lower():
        cm.add_callback(CallbackManager.INSN_BEGIN_CB, handle_insn_begin, name="insn_begin")
        # In order to start a shell, we just need to call start_shell()
        in_kernel = api.is_kernel_running()
        pyrebox_print("Starting a shell after the %s process has been created. In kernel: %s\n" % (name, in_kernel))
        api.start_monitoring_process(pgd)
        start_shell()


def handle_insn_begin(params):
    global cm
    global insns_pased
    global in_kernel
    pyrebox_print("Handling instruction begin. All params: %s\n" % params.keys())
    insns_pased += 1
    if insns_pased > 1000000:
        pyrebox_print("Too many instructions\n")
        cm.rm_callback("insn_begin")
    if insns_pased == 10000:
        start_shell()


    cpu_index = params["cpu_index"]
    cpu = params["cpu"]

    pgd = api.get_running_process(cpu_index)
    pyrebox_print("INSN No: %d, pgd: %x,PC: %x, RIP: %x\n" % (insns_pased, pgd, cpu.PC, cpu.RIP))
    if api.is_kernel_running() is not in_kernel:
        in_kernel = api.is_kernel_running()
        pyrebox_print("Moved in/out of kernel. Running shell\n")
        start_shell()

    # start_shell()

def clean():
    '''
    Clean up everything.

    This function is called when the script is
    unloaded.

    It is necessary to call the clean() function
    in  the callback manager, that will unregister
    all the registered callbacks. Otherwise, the
    next time the callback is triggered, it will
    try to call to a non existent function and
    PyREbox will crash.

    Here you may clean or log whatever you consider
    necessary.
    '''
    global cm
    print("[*]    Cleaning module")
    cm.clean()
    print("[*]    Cleaned module")


def initialize_callbacks(module_hdl, printer):
    '''
    Initilize callbacks for this module. This function
    will be triggered whenever import_module command
    is triggered.
    '''
    global cm
    global pyrebox_print
    # Initialize printer function (global var), that we can use to print
    # text that is associated to our script
    pyrebox_print = printer
    pyrebox_print("[*]    Initializing callbacks")
    # Initialize the callback manager, and register a couple of named
    # callbacks.
    cm = CallbackManager(module_hdl, new_style=True)
    cm.add_callback(CallbackManager.CREATEPROC_CB, handle_new_proc, name="vmi_new_proc")
    # cm.add_callback(CallbackManager.INSN_BEGIN_CB, handle_insn_begin, name="insn_begin")
    pyrebox_print("[*]    Initialized callbacks")


if __name__ == "__main__":
    print("[*] Loading python module %s" % (__file__))

```

**Comment by xabiugarte** [comment] 2019-09-20 08:01
I see that you are generating a trace of the instructions executed, and you mention that the kernel is stuck in an infinite loop. Can you please provide me that trace too? (or at least a small set where you observe the loop, so that I can observe the behavior).

**Comment by bob-hendrix** [comment] 2019-09-20 08:17
Here it is.
[instruction_trace.txt](https://github.com/Cisco-Talos/pyrebox/files/3634856/instruction_trace.txt)

**Comment by xabiugarte** [comment] 2019-09-20 08:32
This seems to be a performance issue. You are tracing a process instruction by instruction, and triggering a python callback each time an instruction is executed, including every instruction executed on the kernel. This a prohibitive in terms of performance.

You can do different things: Set boundaries for the region of instructions you want to trace. For this, you can use the helper BP (breakpoint) class, that allows to set a memory range: https://pyrebox.readthedocs.io/en/latest/api.html#api.BP

Another option is to create triggers yourself. Triggers are small pieces of C/C++ code that are executed before the python callback is called, and allow to prevent this from happening unless certain conditions are met. There are examples in the repository, and documentation: https://pyrebox.readthedocs.io/en/latest/scripting.html#triggers.


Regarding the guest_agent, I would like to follow up to make sure we find out what is happening and why it is not working. Can you describe a little bit more the steps followed and output you get when you try to use the guest_agent, and it crashes?

**Comment by bob-hendrix** [comment] 2019-09-20 08:50
I've waited for longer than 10000 instructions (several millions maximum) with the same behaviour. Also, in the instruction trace exact same sequence seems to be repeaded every 532 instructions.

That being said, what do I need to do in order to get memory range of a process user-mode memory region (to serve as boundaries for breakpionts for example) ?

I can create a new issue for guest agent bug or describe it here, which would be best?

**Comment by xabiugarte** [comment] 2019-09-20 09:21
We can discuss about it here, don't worry. Regarding the memory region, you can use the get_module_list api function: https://pyrebox.readthedocs.io/en/latest/api.html#api.get_module_list
It will return a list of loaded modules (one entry per DLL), and one entry for the main module (executable file, mapped in memory). This main module has the same name as the executable file.

**Comment by bob-hendrix** [comment] 2019-09-20 09:57
About guest agent. I compiled it as per instructions, configuration files with buffer offsets were also created. My pyrepox.conf is:
```
[MODULES]
plugins.guest_agent: True
scripts.script_example: False
scripts.script_example_min: False
scripts.vol_test: False
scripts.proc_bp: False
scripts.mem_write_test: False
scripts.page_write_execute_trigger: False
scripts.getset_var_example: False
scripts.bp_range_test: False
scripts.mem_write_breakpoint_test: False
mw_monitor.mw_monitor: False
pyrebox_test.test_0_vmi_create_proc: False
pyrebox_test.test_1_block_begin: False
pyrebox_test.test_2_opt_block_begin: False
pyrebox_test.test_3_opt_insn_begin: False
pyrebox_test.test_4_mem_write: False
pyrebox_test.test_5_mem_read: False
pyrebox_test.test_6_keystroke: False
pyrebox_test.test_7_nic_test: False
pyrebox_test.test_8_opcode_range: False
pyrebox_test.test_9_tlb_and_context_change: False
pyrebox_test.test_10_block_end: False
pyrebox_test.test_11_insn_end: False
pyrebox_test.test_12_load_remove_module: False

[VOL]
profile: Win7SP1x64_23418 (Also tried with profile Win7SP1x64, no difference)

[AGENT]
name: win_agent_64.exe  (when testing 32 bit version, I've changed theese fields to win_agent_32)
conf: win_agent_64.exe.conf
```
And I start pyrebox with following arguements: -monitor stdio -net none -m 4096 -usb -device usb-tablet -drive file="images/Win7SP1x64.qcow2",index=0,media=disk,format=qcow2,cache=unsafe -vnc 127.0.0.1:9

I've copied guest agents to guest by creating an iso from them and mounting it in guest. When I launch either version of guest_agent, it fails (64 bit crashes, 32 bit says that it's not run under pyrebox). I've tried to use the version of guest_agent.py  that you provided in issue 56, and it prints, that is detected guest_agent. It even detects host_get_version opcode and seems to even increment  RIP correctly (judging from printing cpu before and after incrementing). But guest angent still crashes when I continue vm.

**Comment by xabiugarte** [comment] 2019-09-24 10:04
Hi Bob,

I need to dig into this, as it seems that the latest QEMU update that I merged may be causing some problems. I will write as soon as I find the issue, thank you very much for reporting it!

**Comment by xabiugarte** [comment] 2019-09-25 11:38
Hi Bob, I have fixed the issue now. As I suspected, the problem was introduced when doing the upgrade to QEMU 4.0.

Thank you very much for identifying and isolating the problem.

Please let me know if you have any problems after upgrading, and please reopen this issue if the problem persists.

**Closed by xabiugarte** 2019-09-25 11:38 UTC
